---
schema: "1"
pipeline:
  application: orca
  name: Find Image and Deploy
  template:
    source: file://template.yml
  variables:
    myCustomFirstStageName: "Find Image"
stages:
- id: bake1
  type: findImageFromTags
  name: "{{ myCustomFirstStageName }}"
  config:
    cloudProvider: aws
    cloudProviderType: aws
    packageName: "{{ application }}"
    regions:
    - us-east-1
    - us-west-1
    - us-west-2
    - eu-west-1
    tags:
      stack: test
