schema: "1"
pipeline:             # Combines with the template to make a runnable spinnaker pipeline 
  application: myApp
  name: My super awesome pipeline
  template:
    source: file://child-2-template.yml # What template this config applies to
  variables:           # The actual values for all vars defined in all templates in the chain
    waitTime: 20
    childWaitTime: 15
configuration:        # Configuration of the pipeline
  notifications:
  - address: example@example.com
    level: pipeline
    name: email0
    type: email
    when:
    - pipeline.failed
  triggers: []
stages:
- id: finalwait
  type: wait
  dependsOn:
  - waitChild1
  - waitChild2
  config:
    waitTime: 10